use_frameworks!

target 'FLEXTools_Example' do
  pod 'FLEXTools', :path => '../'

  target 'FLEXTools_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
